include:
- template: Security/SAST.gitlab-ci.yml
- project: 'devops-templates/general-templates'
  ref: 'development'
  file:
    - static-code-analysis/sonar-java.yml
    - devsecops/sast.yml

stages:
  - codequality
  - security_tests
  - automation
  - notify

sast:
  stage: security_tests
  tags:
    - gitlab-runner-docker
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths: [gl-sast-report.json]

test-automation:
  stage: automation
  image: jhonacevedor/quipux-test-automation
  script:
    - ./gradlew clean test --tests CucumberTestSuite -Dproperties=serenity.conf -Dfile.encoding=UTF-8 aggregate || true
  tags:
    - gitlab-runner-docker
  artifacts: # Define la sección de artefactos
    paths:
      - target/ # Ruta del archivo de reporte
  allow_failure: true
  when: always

#notify_email:
#  stage: notify
#  image: python:3.9
#  variables:
#    EMAIL_SUBJECT: "Resultados de Pruebas Automatizadas"
#    EMAIL_MESSAGE: |
#      Las pruebas automatizadas han finalizado correctamente. Por favor, 
#      revisa los resultados en el artefacto generado. Si tienes alguna 
#      pregunta, no dudes en contactarnos.
#  script:
#    - python utils/send_email.py "$EMAIL_SUBJECT" "$EMAIL_MESSAGE" > send_email.log 2>&1
#  when: development
#  artifacts:
#    paths:
#      - send_email.log
#  needs:
#    - job: test-automation
#      artifacts: true
#  tags:
#    - gitlab-runner-docker

google_notification:
  variables:
    EMAIL_SUBJECT: "Resultados de Pruebas Automatizadas"
    EMAIL_MESSAGE: |
      **Resultados de Pruebas Automatizadas**
      
      Las pruebas automatizadas han finalizado correctamente. Por favor, 
      revisa los resultados en el artefacto generado:
      
  stage: notify
  image: python:3.9
  script:
    - previous_job_id=$((CI_JOB_ID - 1))
    - echo $previous_job_id
    - artifact_url="https://git.quipux.com/test-automation/gestion-de-la-atencion/-/jobs/$previous_job_id/artifacts/download?file_type=archive"
    - pip install requests
    - python utils/notificacion_google.py "$EMAIL_MESSAGE" "$GOOGLE_CHAT_API_KEY" "$artifact_url" > send_email.log 2>&1
  when: always
  needs:
    - job: test-automation
      artifacts: true
  artifacts:
    paths:
      - send_email.log
  tags:
    - gitlab-runner-docker

    